config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :members
  resources :contacts do
  	resources :phones
  	resources :alamats
  end

  root to: 'phonebook#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
  validates :nphone, format: { with: /([0][3,8][1][1-9])\w+/ }, length: { minimum: 10 }, presence: true, uniqueness: true

  def self.search(search)
	where('nphone LIKE ? OR 
	 	status LIKE ? OR 
	 	lower(status) LIKE ? OR
	 	upper(status) LIKE ?', 
	 	"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
   end
end

app/controllers/phones_controller.rb
class PhonesController < ApplicationController
	load_and_authorize_resource :contact
	load_and_authorize_resource :phone, :through => :contact

	def new
		@contact = Contact.find(params[:contact_id])
		@phone = @contact.phones.new
	end

	def index
		@contact = Contact.find(params[:contact_id])
		if params[:search]
			@phones = @contact.phones.search(params[:search]).order(:nphone).page(params[:page]).per(5)
		else
			@phones = @contact.phones.order(:nphone).page(params[:page]).per(5)
		end
	end

	def create
		@contact = Contact.find(params[:contact_id])
		@phone = @contact.phones.new(phone_params)
		if @phone.save
		  flash[:success] = "Create Phone Success"
		  redirect_to contact_phones_path(@contact)
		else
		  flash[:danger] = "Create Phone Fail"
	      render "_new.html.erb"
		end
	end

	def edit
		@contact = Contact.find(params[:contact_id])
		@phone = @contact.phones.find(params[:id])
	end

	def update
		@contact = Contact.find(params[:contact_id])
		@phone = @contact.phones.find(params[:id])
	 	if @phone.update(phone_params)
	    	flash[:success] = "Update Phone Success"
	    	redirect_to contact_phones_path(@contact)
	    else
	    	flash[:danger] = "Update Phone Fail"
	    	render "_new.html.erb"
	    end
	end

	def destroy
		@contact = Contact.find(params[:contact_id])
		@phone = @contact.phones.find(params[:id])
		@phone.destroy
		flash[:success] = "Delete Phone Success"
		redirect_to contact_phones_path(@contact)
	end

	private
		def phone_params
			params.require(:phone).permit(:nphone, :status)
		end
end

app/helpers/phones_helper.rb
module PhonesHelper
end

app/views/phones/_form.html.erb
<div class="modal-body">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
  
  <%= form_for([@contact, @phone]) do |f| %>

  <% if @phone.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@phone.errors.count, "error") %> prohibited
        this phone from being saved:
      </h2>
      <ul>
        <% @phone.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <p>
      <%= f.label :phone_number %><br>
      <%= f.text_field :nphone, required: true, pattern: '([0][3,8][1][1-9])\w+' %>
    </p>
    <p>
      <%= f.label :type %><br>
      <%= f.select :status, options_for_select([["Home"],["Fax"],["Mobile"]]) %>
    </p>
    <div class="modal-footer">
      <%= f.submit class: "btn btn-success" %>
      <button type="button" class="btn btn-danger" data-dismiss="modal" onclick="window.location.href='/contacts/<%= @contact.id %>/phones'">Close</button>
    </div>
    <% end %>
</div>

app/views/phones/_new.html.erb
<div id="myModal", class="modal fade", role="dialog">
	<div class=" modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" onclick="window.location.href='/contacts/<%= @contact.id %>/phones'">&times;</button>
				<h4 class="modal-title">Add Phone</h4>
			</div>
			<%= render 'phones/form' %>
		</div>	
	</div>
</div>


<script>
	$("#myModal").modal({backdrop: 'static', keyboard: false},'show')
</script>

app/views/phones/_viewphone.html.erb
<div class="container-fluid">
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th><strong>No</strong></th>
					<th><strong>Type</strong></th>
					<th><strong>Phone</strong></th>
					<th><strong>Option</strong></th>
				</tr>
			</thead>
			<tbody>
				<% @contact.phones.search(params[:search]).order(:nphone).page(params[:page]).per(5).each_with_index do |phone, index| %>
				<tr>
					<td><%= index.next %></td>
					<td><%= phone.status %></td>
					<td><%= phone.nphone %></td>
					<td><button type="button" class="btn btn-success" onclick='edit_phone("<%= phone.id %>")'>Edit</button>
					<%= link_to "<button class='btn btn-danger'>Delete</button>".html_safe, [phone.contact, phone], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button', :id => 'button7' %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/phones/edit.js.erb
$("#show_form").html("<%= escape_javascript(render 'phones/new')%>");

app/views/phones/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= form_tag(contact_phones_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Phones" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<%= render 'phones/viewphone'%>

<button type="button" class="btn btn-info" onclick="new_phone()">Add Phone</button>

<%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, contacts_path , :class => 'button', :id => 'button7' %>

<div align="center">
	<%= paginate @phones %>
</div>

<div id="show_form">

</div>

<script>
	function new_phone(){
		$.get("<%= new_contact_phone_path %>",{},null,"script");
	}

	function edit_phone(id){
		$.get("/contacts/<%= @contact.id %>/phones/"+id+"/edit",{},null,"script");
	}
</script>

app/views/phones/new.js.erb
$("#show_form").html("<%= escape_javascript(render 'phones/new')%>");