config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :members
  resources :contacts do
  	resources :phones
  	resources :alamats
  end

  root to: 'phonebook#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
	belongs_to :user
	has_many :phones, dependent: :destroy
	has_many :alamats, dependent: :destroy
	validates :name, length: { minimum: 6, maximum: 25 }, presence: true, uniqueness: true
	before_save :downcase_fields

	accepts_nested_attributes_for :phones, allow_destroy: true
	accepts_nested_attributes_for :alamats, allow_destroy: true

	has_attached_file :avatar, styles: { medium: "250x250>", thumb: "50x50>"}, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

   def self.search(search)
   	search.downcase!
	where('lower(name) LIKE ? OR 
	 	upper(name) LIKE ? OR 
	 	name LIKE ? OR 
	 	phones.nphone LIKE ? OR 
	 	alamats.address LIKE ? OR
	 	lower(alamats.address) LIKE ? OR
	 	upper(alamats.address) LIKE ?', 
	 	"%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%") 
   end

   def downcase_fields(search)
  	self.name.downcase!
   end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
	load_and_authorize_resource 
	
	def index
		if params[:search]
			@contacts = Contact.joins("LEFT JOIN phones ON phones.contact_id = contacts.id LEFT JOIN alamats ON alamats.contact_id = contacts.id").distinct.search(params[:search]).order(:name)
			.accessible_by(current_ability).page(params[:page]).per(5)	
		else
			@contacts = Contact.order(:name).accessible_by(current_ability).page(params[:page]).per(5)
		end
	end

	def new
		@contact = Contact.new
	end

	def edit
	  	@contact = Contact.find(params[:id])
	end

	def update
	    @contact = Contact.find(params[:id])
		if @contact.update(contact_params)
	    	flash[:success] = "Update Contact Success"
	    	redirect_to contacts_path 
	    else
	    	flash[:danger] = "Update Contact Failed"
	    	render :edit
	    end
	end

	def create
		@contact = current_user.contacts.new(contact_params)
		if @contact.save
		  flash[:success] = "Create Contact Success"
		  redirect_to contacts_path
		else
		  flash[:danger] = "Create Contact Failed"
		  render :new
		end
	end

	def destroy
	   @contact = Contact.find(params[:id])
	   @contact.destroy

	   flash[:success] = "Delete Contact Success"
	   redirect_to contacts_path
	end

	private
		def contact_params
			params.require(:contact).permit(:name, :avatar, phones_attributes: [:id, :nphone, :status, :_destroy], alamats_attributes: [:id, :address, :_destroy])
		end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
  <%= form_for @contact do |f| %>

  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@contact.errors.count, "error") %> prohibited
        this contact from being saved:
      </h2>
      <ul>
        <% @contact.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div><a class="btn btn-info" onclick="add_phone();">Add Phone</a>
       <a class="btn btn-info" onclick="add_address();">Add Address</a></div>

<div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Avatar</th>
        </tr>
      </thead>
      <% indexp = 0 %><% indexa = 0 %>
      <div class="form-group">
      <tbody>
        <tr>
          <td><%= f.file_field :avatar %></td></tr><br>
          <tr><th>Name</th></tr><tr>
          <td><%= f.text_field :name, minlength: 6, maxlength:25 %></td></tr>
      </tbody>

      <tbody id="add_phone">
      <tr><th>Phone</th></tr>
      <%= f.fields_for :phones do |phone| %>
          <tr id="phone_<%= indexp %>">
            <td>
                <%= phone.text_field :nphone, required: true, pattern: '([0][3,8][1][1-9])\w+' %>
                <%= phone.label :type %>
                <%= phone.select :status, options_for_select([["Home"],["Fax"],["Mobile"]]) %>
                <a onclick="delete_phone(<%= indexp %>);" class="btn btn-danger">Delete</a>
            </td>
              <% indexp = indexp + 1 %>
          </tr>
          <% end %>
        </tbody>
        <tbody id="add_address">
          <tr><th>Address</th></tr>
          <%= f.fields_for :alamats do |alamat| %>
          <tr id= "address_<%= indexa %>">
          <td>
               <%= alamat.text_field :address, required: true, minlength: 15, maxlength:30 %>
               <a onclick="delete_address(<%= indexa %>);" class="btn btn-danger">Delete</a>
            </td><% indexa = indexa + 1 %></tr><% end %>
      </tbody>
      </div>
    </table>
  </div>

<%= f.submit class: "btn btn-success" %>
<%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, contacts_path, :class => 'button', :id => 'button3' %>

<% end %>

<script>

  id_phone = <%= @contact.phones.count %>
  id_address = <%= @contact.alamats.count %>

  function add_phone(){

      id_phone = id_phone + 1;

      data = "<tr id='phone_"+id_phone+"'><td>"

      data += "<input pattern= '([0][3,8][1][1-9])\\w+' type='text' name='contact[phones_attributes]["+id_phone+"][nphone]' id='contact_phones_attributes_"+id_phone+"_nphone' />"

      data += " <label for='contact_phones_attributes_"+id_phone+"_type'>Type</label> "

      data += "<select name='contact[phones_attributes]["+id_phone+"][status]' id='contact_phones_attributes_"+id_phone+"_status'><option value='Home'>Home</option><option value='Fax'>Fax</option><option value='Mobile'>Mobile</option></select>"

      data += " <a onclick='delete_phone("+id_phone+");' class='btn btn-danger'>Delete</a></td></tr>"

    $("#add_phone").append(data).html_safe;
  }

  function delete_phone(id){
    data = "<input type='hidden' value=1 name='contact[phones_attributes]["+id+"][_destroy]'>"
    $("#add_phone").append(data);
    $("#phone_"+id).remove();
  }

  function add_address(){

    id_address = id_address + 1;

    data = "<tr id='address_"+id_address+"'><td>"

    data += "<input required='required' minlength='15' maxlength='30' size='30' type='text' value= '' name='contact[alamats_attributes]["+id_address+"][address]' id='contact_alamats_attributes_"+id_address+"_address' />"

    data += " <a onclick='delete_address("+id_address+");' class='btn btn-danger'>Delete</a></td></tr>"

    $("#add_address").append(data).html_safe;
  }

  function delete_address(id){
    data = "<input type='hidden' value=1 name='contact[alamats_attributes]["+id+"][_destroy]'>"
    $("#add_address").append(data);
    $("#address_"+id).remove();
  }
</script>

app/views/contacts/edit.html.erb
<nav class="navbar-default navbar-static=top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1> <a class="navbar-brand" href="/">Phonebook</a></h1>     
  </div>
  <div class="border-bottom">
    <div class="full-left">
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li><a href="/" class="hvr-bounce-to-right"><i class="fa fa-home nav_icon" aria-hidden="true"></i><span class="nav-label"> Dashboard </span></a></li>

        <% if user_signed_in? %>
          <li><a href="/contacts" class="hvr-bounce-to-right"><i class="fa fa-phone nav_icon"></i><span class="nav-label"> Contacts </span></a></li>

          <li><a href="/members" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Users </span></a></li>

          <li><a href="/users/edit" class="hvr-bounce-to-right"><i class="fa fa-star nav_icon"></i><span class="nav-label"><%= current_user.email %></span></a></li>

          <li><a data-confirm="Are You Sure?" href="/users/sign_out" data-method="delete" class="hvr-bounce-to-right"><i class="fa fa-arrow-left nav_icon"></i><span class="nav-label"> Logout </span></a></li>
          <% else %>
          <li><a href="/users/sign_up" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Signup </span></a></li>
          <li><a href="/users/sign_in" class="hvr-bounce-to-right"><i class="fa fa-arrow-right nav_icon"></i><span class="nav-label"> Login </span></a></li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>
</nav>
<div id="page-wrapper" class="gray-bg dashboard-1">
  <div class="content-main">
    <div class="banner">
      <h2>
        <a href="/">Home</a>
        <i class="fa fa-chevron-right"></i>
        <a href="/contacts">Contacts</a> 
        <i class="fa fa-chevron-right"></i>
        <span>Edit</span> 
      </h2>
    </div>
    <div class="content-top">
      <div class="col-md-12">
        <div class="content-top-1">
        	<% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>

			<h1>Edit Contact</h1>

			<%= render 'form' %>
		</div><br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<nav class="navbar-default navbar-static=top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1> <a class="navbar-brand" href="/">Phonebook</a></h1>     
  </div>
  <div class="border-bottom">
    <div class="full-left">
      <form class="navbar-left-right" id="search-form" action="/contacts" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
      <input type="text" name="search" id="search" placeholder="Search Contacts" />
      <input type="submit" value="&#xf002;" data-disable-with="Search" />
  </form>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li><a href="/" class="hvr-bounce-to-right"><i class="fa fa-home nav_icon" aria-hidden="true"></i><span class="nav-label"> Dashboard </span></a></li>

        <% if user_signed_in? %>
          <li><a href="/contacts" class="hvr-bounce-to-right"><i class="fa fa-phone nav_icon"></i><span class="nav-label"> Contacts </span></a></li>

          <li><a href="/members" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Users </span></a></li>

          <li><a href="/users/edit" class="hvr-bounce-to-right"><i class="fa fa-star nav_icon"></i><span class="nav-label"><%= current_user.email %></span></a></li>

          <li><a data-confirm="Are You Sure?" href="/users/sign_out" data-method="delete" class="hvr-bounce-to-right"><i class="fa fa-arrow-left nav_icon"></i><span class="nav-label"> Logout </span></a></li>
          <% else %>
          <li><a href="/users/sign_up" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Signup </span></a></li>
          <li><a href="/users/sign_in" class="hvr-bounce-to-right"><i class="fa fa-arrow-right nav_icon"></i><span class="nav-label"> Login </span></a></li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>
</nav>
<div id="page-wrapper" class="gray-bg dashboard-1">
  <div class="content-main">
    <div class="banner">
      <h2>
        <a href="/">Home</a>
        <i class="fa fa-chevron-right"></i>
        <span>Contacts</span> 
      </h2>
    </div>
    <div class="content-top">
      <div class="col-md-12">
        <div class="content-top-1">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <h1>Contacts</h1><br>
          <div class="table-responsive">
  <table class="table table-bordered table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Phone</th>
        <th>Address</th>
        <th>Option</th>
      </tr>
    </thead>
    <tbody>
      <% @contacts.each do |contact| %>
        <tr>
          <td> <%= image_tag contact.avatar.url(:thumb) %> <%= contact.name %></td>
          <td><%= contact.phones.count %></td>
          <td><%= contact.alamats.count %></td>
          <td><%= link_to "<button class='btn btn-success'>Add Phone</button>".html_safe, contact_phones_path(contact), :class => 'button', :id => 'button4' %>

          <%= link_to "<button class='btn btn-success'>Add Address</button>".html_safe, contact_alamats_path(contact), :class => 'button', :id => 'button10' %>

          <% if can? :edit, contact %>
          <%= link_to "<button class='btn btn-primary'>Edit</button>".html_safe, edit_contact_path(contact), :class => 'button', :id => 'button5' %>
          <% end %>

          <% if can? :destroy, contact %>
          <%= link_to "<button class='btn btn-danger'>Destroy</button>".html_safe, contact_path(contact),
            method: :delete,
            data: { confirm: 'Are you sure?' }, :class => 'button', :id => 'button6' %>
          <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div><br>
          <%= link_to "<button class='btn btn-info'>Add Contact</button>".html_safe, new_contact_path, :class => 'button', :id => 'button' %>
          <div id="show_form"></div>
          <div class="text-center"><%= paginate @contacts %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<nav class="navbar-default navbar-static=top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1> <a class="navbar-brand" href="/">Phonebook</a></h1>     
  </div>
  <div class="border-bottom">
    <div class="full-left">
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li><a href="/" class="hvr-bounce-to-right"><i class="fa fa-home nav_icon" aria-hidden="true"></i><span class="nav-label"> Dashboard </span></a></li>

        <% if user_signed_in? %>
          <li><a href="/contacts" class="hvr-bounce-to-right"><i class="fa fa-phone nav_icon"></i><span class="nav-label"> Contacts </span></a></li>

          <li><a href="/members" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Users </span></a></li>

          <li><a href="/users/edit" class="hvr-bounce-to-right"><i class="fa fa-star nav_icon"></i><span class="nav-label"><%= current_user.email %></span></a></li>

          <li><a data-confirm="Are You Sure?" href="/users/sign_out" data-method="delete" class="hvr-bounce-to-right"><i class="fa fa-arrow-left nav_icon"></i><span class="nav-label"> Logout </span></a></li>
          <% else %>
          <li><a href="/users/sign_up" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Signup </span></a></li>
          <li><a href="/users/sign_in" class="hvr-bounce-to-right"><i class="fa fa-arrow-right nav_icon"></i><span class="nav-label"> Login </span></a></li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>
</nav>
<div id="page-wrapper" class="gray-bg dashboard-1">
  <div class="content-main">
    <div class="banner">
      <h2>
        <a href="/">Home</a>
        <i class="fa fa-chevron-right"></i>
        <a href="/contacts">Contacts</a> 
        <i class="fa fa-chevron-right"></i>
        <span>New</span> 
      </h2>
    </div>
    <div class="content-top">
      <div class="col-md-12">
        <div class="content-top-1">
        	<% flash.each do |key, value| %>
			  <div class="alert alert-<%= key %>"><%= value %></div>
			<% end %>

			<h1>New Contact</h1>

			<%= render 'form' %>
		</div><br>
        </div>
      </div>
    </div>
  </div>
</div>