config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :members
  resources :contacts do
  	resources :phones
  	resources :alamats
  end

  root to: 'phonebook#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alamat.rb
class Alamat < ApplicationRecord
  belongs_to :contact
  validates :address, length: { minimum:20, maximum: 50 }, presence: true, uniqueness: true
  before_save :downcase_fields

  def self.search(search)
	where('address LIKE ? OR  
	 	lower(address) LIKE ? OR
	 	upper(address) LIKE ?', 
	 	"%#{search}%", "%#{search}%", "%#{search}%") 
   end

   def downcase_fields
  	self.address.downcase!
   end
end

app/controllers/alamats_controller.rb
class AlamatsController < ApplicationController
  load_and_authorize_resource :contact
  load_and_authorize_resource :alamat, :through => :contact

  def new
    @contact = Contact.find(params[:contact_id])
    @alamat = @contact.alamats.new
  end

  def edit
    @contact = Contact.find(params[:contact_id])
    @alamat = @contact.alamats.find(params[:id])
  end

  def update
    binding.pry
    @contact = Contact.find(params[:contact_id])
    @alamat = @contact.alamats.find(params[:id])
   
      if @alamat.update(alamat_params)
        flash[:success] = "Update Address Success"
        redirect_to contact_alamats_path(@contact)
      else
        flash[:danger] = "Update Address Fail"
        render "_new.html.erb"
      end
  end

  def index
    @contact = Contact.find(params[:contact_id])
    if params[:search]
      @alamats = @contact.alamats.search(params[:search].downcase!).order(:address).page(params[:page]).per(5)
    else
      @alamats = @contact.alamats.order(:address).page(params[:page]).per(5)
    end
  end

  def create
    @contact = Contact.find(params[:contact_id])
    @alamat = @contact.alamats.create(alamat_params)
    if @alamat.save
      flash[:success] = "Create Address Success"
      redirect_to contact_alamats_path(@contact)
    else
      flash[:danger] = "Create Address Fail"
        render "_new.html.erb"
    end
  end

  def destroy
    @contact = Contact.find(params[:contact_id])
    @alamat = @contact.alamats.find(params[:id])
    @alamat.destroy
    flash[:success] = "Delete Address Success"
    redirect_to contact_alamats_path(@contact)
  end

  private
    def alamat_params
      params.require(:alamat).permit(:address)
    end
end

app/helpers/alamats_helper.rb
module AlamatsHelper
end

app/views/alamats/_alamat.html.erb
<% @contact.alamats.search(params[:search]).order(:address).page(params[:page]).per(5).each_with_index do |alamat, index|%>
	<tr>
		<td><%= index.next %></td>
		<td><%= alamat.address %></td>
		<td><button type="button" class="btn btn-success" onclick='edit_alamat("<%= alamat.id %>")'>Edit</button>
		<%= link_to "<button class='btn btn-danger'>Delete</button>".html_safe, [alamat.contact, alamat], method: :delete, data: { confirm: 'Are you sure?' }, :class => 'button', :id => 'button8' %></td>
	</tr>
<% end %>

app/views/alamats/_form.html.erb
<div class="modal-body">

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %> 

<%= form_for([@contact, @alamat]) do |f| %>

<% if @alamat.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@alamat.errors.count, "error") %> prohibited
        this address from being saved:
      </h2>
      <ul>
        <% @alamat.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :Address %><br>
    <%= f.text_field :address, required: true, minlength: 15, maxlength:30 %>
  </p>
  <div class="modal-footer">
	<%= f.submit class: 'btn btn-success' %>
	<button type="button" class="btn btn-danger" data-dismiss="modal" onclick="window.location.href='/contacts/<%= @contact.id %>/alamats'">Close</button>
  </div>
  <% end %>
</div>

app/views/alamats/_new.html.erb
<div id="myModal", class="modal fade", role="dialog">
	<div class=" modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" onclick="window.location.href='/contacts/<%= @contact.id %>/alamats'">&times;</button>
				<h4 class="modal-title">Add Address</h4>
			</div>
			<%= render 'alamats/form' %>
		</div>
	</div>
</div>

<script>
	$("#myModal").modal({backdrop: 'static', keyboard: false},'show')
</script>

app/views/alamats/_viewalamat.html.erb
<div class="container-fluid">
	<div class="table-responsive">
		<table class="table">
			<thead>
				<tr>
					<th><strong>No</strong></th>
					<th><strong>Address</strong></th>
					<th><strong>Option</strong></th>
				</tr>
			</thead>
			<tbody>
				<%= render "alamats/alamat" %>
			</tbody>
		</table>
	</div>
</div>

app/views/alamats/edit.js.erb
$("#show_form").html("<%= escape_javascript(render 'alamats/new')%>");

app/views/alamats/index.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>

<%= form_tag(contact_alamats_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Address" %>
    <%= submit_tag "Search", :name => nil %>
<% end %>

<%= render 'alamats/viewalamat'%>

<button type="button" class="btn btn-info" onclick="new_alamat()">Add Address</button>

<%= link_to "<button class='btn btn-danger'>Back</button>".html_safe, contacts_path , :class => 'button', :id => 'button7' %>

<div align="center">
	<%= paginate @alamats %>
</div>

<div id="show_form">

</div>

<script>
	function new_alamat(){
		$.get("<%= new_contact_alamat_path %>",{},null,"script");
	}

	function edit_alamat(id){
		$.get("/contacts/<%= @contact.id %>/alamats/"+id+"/edit",{},null,"script");
	}
</script>

app/views/alamats/new.js.erb
$("#show_form").html("<%= escape_javascript(render 'alamats/new')%>");