config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :members
  resources :contacts do
  	resources :phones
  	resources :alamats
  end

  root to: 'phonebook#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
	load_and_authorize_resource :class => User
	
	def index
		if params[:search]
			@members = User.search(params[:search]).page(params[:page]).per(5)
		else
			@members = User.all.page(params[:page]).per(5)
		end
	end

	def new
		@member = User.new
	end

	def create
		@member = User.new(member_params)
		if @member.save
		  flash[:success] = "Create User Success"
		  redirect_to members_path
		else
		  flash[:danger] = "Create User Failed"
		  render "_new.html.erb"
		end
	end

	def edit
	   @member = User.find(params[:id])
	end

	def update
		@member = User.find(params[:id])
	 
		if params[:user][:password].blank?
			params[:user].delete :password
			params[:user].delete :password_confirmation
		end

	    if @member.update(member_params)
	    	flash[:success] = "Update User Success"
	    	redirect_to members_path 
	    else
	    	flash[:danger] = "Update User Failed"
	    	render "_edit.html.erb"
	    end
	end

	def destroy
	   @member = User.find(params[:id])

	   if current_user == @member
	   	flash[:danger] = "User Online"
	   else
	   	@member.destroy
	   	flash[:success] = "Delete User Success"
	   end

	   redirect_to members_path
	end

	private
	def member_params
		params.require(:user).permit(:email, :password, :admin)
	end

end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_edit.html.erb
<div id="myModal", class="modal fade", role="dialog">
	<div class=" modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" onclick="window.location.href='/members/'">&times;</button>
				<h4 class="modal-title">Add Phone</h4>
			</div>
				<div class="modal-body">
				<%= form_for @member , url: member_path, method: :patch do |f| %>
				  <form>
				    <div class="form-group">
				      <%= f.label :email, for:'email' %><br />
				      <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder:'Enter email', id:'email' %>
				    </div>
				    <div class="form-group">
				      <%= f.label :password, for:'pwd' %>
				      <% if @minimum_password_length %>
				      <em>(<%= @minimum_password_length %> characters minimum)</em>
				      <% end %><br />
				      <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder:'Enter password', id:'pwd' %>
				    </div>
				    <div class="form-group">
				      <%= f.label :password_confirmation, for:'pwd_confirm' %><br />
				      <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder:'Enter confirmation password', id:'pwd_confirm' %>
				    </div>
				    <div class="form-group">
				      <%= f.label :admin %> <br />
				      <%= f.radio_button :admin, true %> Yes <br />
				      <%= f.radio_button :admin, false %> No
				    </div>
				  <div class="modal-footer">
					<%= f.submit class: 'btn btn-success' %>
					<button type="button" class="btn btn-danger" data-dismiss="modal" onclick="window.location.href='/members/'">Close</button>
				  </div>
				  <% end %>
				</div>
		</div>	
	</div>
</div>


<script>
	$("#myModal").modal({backdrop: 'static', keyboard: false},'show')
</script>

app/views/members/_form.html.erb
<div class="modal-body">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
<%= form_for @member, url: members_path, method: :post do |f| %>
  <form>
    <div class="form-group">
      <%= f.label :email, for:'email' %><br />
      <%= f.email_field :email, autofocus: true, class: 'form-control', placeholder:'Enter email', id:'email' %>
    </div>
    <div class="form-group">
      <%= f.label :password, for:'pwd' %>
      <% if @minimum_password_length %>
      <em>(<%= @minimum_password_length %> characters minimum)</em>
      <% end %><br />
      <%= f.password_field :password, autocomplete: "off", class: 'form-control', placeholder:'Enter password', id:'pwd' %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, for:'pwd_confirm' %><br />
      <%= f.password_field :password_confirmation, autocomplete: "off", class: 'form-control', placeholder:'Enter confirmation password', id:'pwd_confirm' %>
    </div>
    <div class="form-group">
      <%= f.label :admin %> <br />
      <%= f.radio_button :admin, true %> Yes <br />
      <%= f.radio_button :admin, false %> No
    </div>
  <div class="modal-footer">
	<%= f.submit class: 'btn btn-success' %>
	<button type="button" class="btn btn-danger" data-dismiss="modal" onclick="window.location.href='/members/'">Close</button>
  </div>
  <% end %>
</div>

app/views/members/_new.html.erb
<div id="myModal", class="modal fade", role="dialog">
	<div class=" modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" onclick="window.location.href='/members/'">&times;</button>
				<h4 class="modal-title">Add User</h4>
			</div>
			<%= render 'form' %>
		</div>	
	</div>
</div>


<script>
	$("#myModal").modal({backdrop: 'static', keyboard: false},'show')
</script>

app/views/members/edit.js.erb
$("#show_form").html("<%= escape_javascript(render 'members/edit')%>");

app/views/members/index.html.erb
<nav class="navbar-default navbar-static=top" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <h1> <a class="navbar-brand" href="/">Phonebook</a></h1>     
  </div>
  <div class="border-bottom">
    <div class="full-left">
      <form class="navbar-left-right" id="search-form" action="/members" accept-charset="UTF-8" method="get"><input name="utf8" type="hidden" value="&#x2713;" />
      <input type="text" name="search" id="search" placeholder="Search Users" />
      <input type="submit" value="&#xf002;" data-disable-with="Search" />
  </form>
      <div class="clearfix"></div>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <li><a href="/" class="hvr-bounce-to-right"><i class="fa fa-home nav_icon" aria-hidden="true"></i><span class="nav-label"> Dashboard </span></a></li>

        <% if user_signed_in? %>
          <li><a href="/contacts" class="hvr-bounce-to-right"><i class="fa fa-phone nav_icon"></i><span class="nav-label"> Contacts </span></a></li>

          <li><a href="/members" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Users </span></a></li>

          <li><a href="/users/edit" class="hvr-bounce-to-right"><i class="fa fa-star nav_icon"></i><span class="nav-label"><%= current_user.email %></span></a></li>

          <li><a data-confirm="Are You Sure?" href="/users/sign_out" data-method="delete" class="hvr-bounce-to-right"><i class="fa fa-arrow-left nav_icon"></i><span class="nav-label"> Logout </span></a></li>
          <% else %>
          <li><a href="/users/sign_up" class="hvr-bounce-to-right"><i class="fa fa-user nav_icon"></i><span class="nav-label"> Signup </span></a></li>
          <li><a href="/users/sign_in" class="hvr-bounce-to-right"><i class="fa fa-arrow-right nav_icon"></i><span class="nav-label"> Login </span></a></li>
        <% end %>
      </ul>
      <div class="clearfix"></div>
    </div>
  </div>
</nav>
<div id="page-wrapper" class="gray-bg dashboard-1">
  <div class="content-main">
    <div class="banner">
      <h2>
        <a href="/">Home</a>
        <i class="fa fa-chevron-right"></i>
        <span>User</span> 
      </h2>
    </div>
    <div class="content-top">
      <div class="col-md-12">
        <div class="content-top-1">
          <% flash.each do |key, value| %>
            <div class="alert alert-<%= key %>"><%= value %></div>
          <% end %>
          <h1>Users</h1><br>
          <div class="table-responsive">
            <table class="table table-bordered table-hover">
              <thead>
                <tr>
                  <th>Email</th>
                  <th>Admin</th>
                  <th>Created At</th>
                  <th>Option</th>
                </tr>
              </thead>
              <tbody>
                <% @members.each do |member| %>
                  <tr>
                <td><%= member.email %></td>
                <td><%= member.admin %></td>
                <td><%= member.created_at.strftime("%A, %b %-d %Y, %T WIB") %></td>
                <td>
                    <button type="button" class="btn btn-info" onclick='edit_user("<%= member.id %>")'>Edit</button>

                    <%= link_to "<button class='btn btn-danger'>Destroy</button>".html_safe, member_path(member),
                      method: :delete,
                      data: { confirm: 'Are you sure?' }, :class => 'button', :id => 'button6' %>
                </td>
              </tr>
            <% end %>
              </tbody>
            </table>
          </div><br>
          <button type="button" class="btn btn-success" onclick="new_user()"> Add User</button>
          <div id="show_form"></div>
          <div class="text-center"><%= paginate @members %></div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function new_user(){
    $.get("<%= new_member_path %>",{},null,"script");
  }
  function edit_user(id){
    $.get("/members/"+id+"/edit",{},null,"script");
  }
</script>

app/views/members/new.js.erb
$("#show_form").html("<%= escape_javascript(render 'members/new')%>");